# Generated by Django 5.1.2 on 2024-11-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='publication_year',
        ),
    ]
